import React, { useState } from 'react';
import { Download, FileSpreadsheet, Upload } from 'lucide-react';
import { api } from '../../api';

const templates: Record<string, Record<string, string>[]> = {
  users: [{ name: 'Example User', email: 'user@example.com', role: 'Sales KAM', department: 'Sales', salesTeam: 'Enterprise Team', region: 'Bangladesh', password: '' }],
  clients: [{ code: 'CL-001', name: 'Example Client', industry: 'Corporate', headquarters: 'Dhaka', assignedSalesKAM: 'Sales KAM Name' }],
  opportunities: [{ code: 'OPP-001', name: 'Example Opportunity', clientName: 'Example Client', stage: 'qualification', contractValue: '0', arr: '0', winProbability: '0', accountExecutive: 'Sales KAM Name', leadSolutionArchitect: 'Presales Engineer' }],
  opportunity_updates: [{ opportunityCode: 'OPP-001', type: 'Client Meeting', title: 'Initial discussion', summary: 'Meeting notes', nextAction: 'Prepare proposal', nextFollowUpDate: '2026-09-15' }],
};

export const BulkUploadView: React.FC = () => {
  const [entity, setEntity] = useState('users');
  const [rows, setRows] = useState<Record<string, unknown>[]>([]);
  const [message, setMessage] = useState('');
  const downloadTemplate = () => { const sample = templates[entity]; const headers = Object.keys(sample[0]); const csv = [headers.join(','), ...sample.map(row => headers.map(key => JSON.stringify(row[key] ?? '')).join(','))].join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); link.download = `presales_${entity}_template.csv`; link.click(); URL.revokeObjectURL(link.href); };
  const handleFile = async (file?: File) => { if (!file) return; try { const lines = (await file.text()).split(/\r?\n/).filter(Boolean); if (lines.length < 2) throw new Error('empty'); const parse = (line: string) => line.match(/(?:^|,)\s*(?:"((?:[^"]|"")*)"|([^,]*))/g)?.map(value => value.replace(/^,\s*/, '').replace(/^"|"$/g, '').replace(/""/g, '')) || []; const headers = parse(lines[0]); const parsed = lines.slice(1).map(line => { const values = parse(line); return Object.fromEntries(headers.map((header, index) => [header, values[index] ?? ''])); }); setRows(parsed); setMessage(`${parsed.length} rows ready to preview.`); } catch { setMessage('Could not read this CSV file.'); } };
  const upload = async () => { if (!rows.length) return; setMessage('Uploading...'); try { const result = await api.bulkImport(entity, rows); setMessage(`Completed: ${result.created} created, ${result.updated} updated${result.errors.length ? `, ${result.errors.length} rejected` : ''}.`); setRows([]); } catch { setMessage('Upload failed. Check permissions and template columns.'); } };
  return <div className="space-y-4 max-w-4xl mx-auto"><div className="bg-white border border-gray-200 rounded p-4"><div className="flex items-center gap-2"><FileSpreadsheet className="w-5 h-5 text-blue-600" /><div><h1 className="text-base font-bold text-gray-900">Bulk CSV Upload</h1><p className="text-xs text-gray-500">Import users, clients, opportunities, or opportunity updates.</p></div></div></div><div className="bg-white border border-gray-200 rounded p-4 space-y-3"><div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><label><span className="block text-[10px] uppercase font-semibold text-gray-500 mb-1">Upload Type</span><select value={entity} onChange={e => { setEntity(e.target.value); setRows([]); setMessage(''); }} className="enterprise-select w-full text-xs"><option value="users">Users</option><option value="clients">Clients</option><option value="opportunities">New Opportunities</option><option value="opportunity_updates">Opportunity Updates</option></select></label><label><span className="block text-[10px] uppercase font-semibold text-gray-500 mb-1">CSV File</span><input type="file" accept=".csv,text/csv" onChange={e => handleFile(e.target.files?.[0])} className="w-full text-xs file:mr-2 file:border-0 file:bg-blue-50 file:px-2 file:py-1 file:text-xs file:font-semibold file:text-blue-700" /></label></div><div className="flex flex-wrap gap-2"><button onClick={downloadTemplate} className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold text-blue-700 bg-blue-50 border border-blue-200 rounded"><Download className="w-3.5 h-3.5" /> Download CSV Template</button>{rows.length > 0 && <button onClick={upload} className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold text-white bg-emerald-600 rounded"><Upload className="w-3.5 h-3.5" /> Upload {rows.length} Rows</button>}</div>{message && <div className="p-2.5 rounded bg-gray-50 border border-gray-200 text-xs text-gray-700">{message}</div>}</div></div>;
};
