import React from 'react';
import { BarChart3, CheckCircle2, FileCheck, TrendingUp } from 'lucide-react';
import { ActiveTab, Opportunity } from '../../types';
import { formatCurrency } from '../../utils/currency';

export const MobileReportsScreen: React.FC<{ opportunities: Opportunity[]; onNavigateTab: (tab: ActiveTab) => void }> = ({ opportunities, onNavigateTab }) => {
  const won = opportunities.filter(o => o.stage === 'closed_won').length;
  const lost = opportunities.filter(o => o.stage === 'closed_lost').length;
  const activities = opportunities.reduce((total, opportunity) => total + (opportunity.activities || []).length, 0);
  const boqValue = opportunities.reduce((total, opportunity) => total + (opportunity.boq?.totalContractValue || 0), 0);
  return <div className="space-y-3 pb-2"><header className="bg-white border border-gray-200 rounded p-4"><div className="flex items-center gap-2"><BarChart3 className="w-5 h-5 text-cyan-600" /><div><h1 className="text-base font-bold text-gray-900">Reports & Analytics</h1><p className="text-xs text-gray-500">Live presales performance summary.</p></div></div></header><div className="grid grid-cols-2 gap-2">{[{ label: 'Pipeline', value: formatCurrency(opportunities.reduce((total, o) => total + (o.contractValue || 0), 0)), tone: 'text-blue-700' }, { label: 'Won', value: won, tone: 'text-emerald-700' }, { label: 'Lost', value: lost, tone: 'text-red-700' }, { label: 'Activities', value: activities, tone: 'text-purple-700' }, { label: 'BOQ Value', value: formatCurrency(boqValue), tone: 'text-amber-700' }].map(metric => <div key={metric.label} className="bg-white border border-gray-200 rounded p-3"><div className="text-[10px] uppercase text-gray-500 font-semibold">{metric.label}</div><div className={`text-lg font-bold font-mono mt-1 ${metric.tone}`}>{metric.value}</div></div>)}</div><div className="grid grid-cols-2 gap-2"><button onClick={() => onNavigateTab('opportunities')} className="bg-white border border-gray-200 rounded p-3 text-left"><TrendingUp className="w-4 h-4 text-blue-600" /><div className="text-xs font-semibold mt-2">Pipeline Report</div></button><button onClick={() => onNavigateTab('boq_workbench')} className="bg-white border border-gray-200 rounded p-3 text-left"><FileCheck className="w-4 h-4 text-purple-600" /><div className="text-xs font-semibold mt-2">BOQ Report</div></button></div><div className="bg-emerald-50 border border-emerald-200 rounded p-3 flex items-center gap-2 text-xs text-emerald-800"><CheckCircle2 className="w-4 h-4" /> Metrics are calculated from current opportunity records.</div></div>;
};
