import { Opportunity } from '../types';

/**
 * Trigger a browser download of a text blob
 */
function downloadBlob(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Export complete Opportunity SADD (Solution Architecture Design Document) as Markdown
 */
export function exportOpportunitySADDMarkdown(opp: Opportunity) {
  const md = `# Solution Architecture Design Document (SADD)
## Project: ${opp.name} (${opp.code})
**Client:** ${opp.clientName} | **Industry:** ${opp.clientIndustry} | **Region:** ${opp.region}
**Lead Solution Architect:** ${opp.leadSolutionArchitect}
**Sales Account Executive (KAM):** ${opp.accountExecutive}
**Document Generated:** ${new Date().toISOString().slice(0, 10)}
**Deal Stage:** ${opp.stage.toUpperCase()} | **Contract Value (TCV):** $${opp.contractValue.toLocaleString()} | **ARR:** $${opp.arr.toLocaleString()}

---

### 1. Existing Infrastructure & Legacy Baseline
${opp.currentLegacyStack}

### 2. Proposed Target Architecture & Solution Overview
- **Primary Tech Stack:** ${opp.primaryTechStack || 'N/A'}
- **Secondary Technologies:** ${(opp.technologies || []).join(', ')}
- **Technical Fit Assessment:** ${opp.technicalFitScore ?? 'N/A'}/100
- **Architecture Blueprint Description:**
${opp.proposedArchitecture || 'Pending architecture blueprint.'}

### 3. Key Non-Functional & Architecture Requirements
${(opp.keyTechnicalRequirements || []).map(req => `- ${req}`).join('\n')}

### 4. Compliance & Security Clearances
- **Required Frameworks:** ${(opp.complianceRequirements || []).join(', ')}
- **Security Audit Status:** ${opp.securityReviewStatus || 'Pending'}

### 5. Stakeholder & Decision Maker Matrix
| Name | Role | Department | Sentiment | Influence | Buying Role |
|------|------|------------|-----------|-----------|-------------|
${(opp.stakeholders || []).map(s => `| ${s.name} | ${s.role} | ${s.department} | ${s.sentiment} | ${s.influence} | ${s.buyingRole} |`).join('\n')}

### 6. Bill of Quantities (BOQ) Summary (v${opp.boq?.version || 1})
- **Total List Price:** $${(opp.boq?.subtotalListPrice || 0).toLocaleString()}
- **Total Extended Price (TCV):** $${(opp.boq?.totalContractValue || 0).toLocaleString()}
- **Direct Cost:** $${(opp.boq?.subtotalCost || 0).toLocaleString()}
- **Total Concessions/Discount:** $${(opp.boq?.totalDiscountAmount || 0).toLocaleString()}
- **Realized Margin:** ${opp.boq?.overallMarginPercent || 0}%
- **Margin Governance Status:** ${(opp.boq?.approvalStatus || 'pending').toUpperCase()}

#### Detailed Line Items
| SKU / Item Code | Description | Category | Qty & Unit | Unit List | Disc % | Extended Price | Margin |
|-----------------|-------------|----------|------------|-----------|--------|----------------|--------|
${(opp.boq?.items || []).map(item => `| ${item.itemCode} | ${item.description} | ${item.category} | ${item.quantity} ${item.unit} | $${item.unitListPrice} | ${item.discountPercent}% | $${(item.extendedPrice || 0).toLocaleString()} | ${item.marginPercent}% |`).join('\n')}

### 7. Proof of Concept (POC) Validation
- **POC Status:** ${(opp.poc?.status || 'not_started').toUpperCase()}
- **Allocated Sandbox Budget:** $${(opp.poc?.allocatedBudget || 0).toLocaleString()}
${(opp.poc?.successCriteria || []).length > 0 ? `\n#### Success Criteria & KPI Gates:\n${opp.poc.successCriteria.map(sc => `- [${sc.verified ? 'X' : ' '}] **${sc.category}**: ${sc.description} (Target: ${sc.targetMetric})`).join('\n')}` : ''}
${opp.poc?.blockers && opp.poc.blockers.length > 0 ? `\n#### Technical Blockers:\n${opp.poc.blockers.map(b => `- [${b.resolved ? 'RESOLVED' : 'ACTIVE'}] **${b.severity.toUpperCase()}**: ${b.description}`).join('\n')}` : ''}

### 8. Implementation Handover Gate
- **Handover Completed:** ${opp.handover?.isHandedOver ? 'YES' : 'NO'}
- **Technical Runbook Ready:** ${opp.handover?.technicalRunbookReady ? 'YES' : 'NO'}
- **Credentials Securely Transferred:** ${opp.handover?.credentialsSecurelyTransferred ? 'YES' : 'NO'}
- **Customer Kickoff Scheduled:** ${opp.handover?.customerTechKickoffScheduled ? 'YES' : 'NO'}

---
*Generated by Presales Engineering Tracker Enterprise Suite*
`;

  downloadBlob(md, `${opp.code}_SADD_Technical_Architecture.md`, 'text/markdown;charset=utf-8;');
}

/**
 * Export Opportunity full JSON dataset
 */
export function exportOpportunityJSON(opp: Opportunity) {
  const jsonStr = JSON.stringify(opp, null, 2);
  downloadBlob(jsonStr, `${opp.code}_Opportunity_Package.json`, 'application/json;charset=utf-8;');
}

/**
 * Export BOQ to CSV spreadsheet
 */
export function exportBOQCSV(opp: Opportunity) {
  const headers = ['SKU Code', 'Description', 'Category', 'Quantity', 'Unit', 'Unit Cost ($)', 'Unit List Price ($)', 'Discount (%)', 'Extended Price ($)', 'Margin (%)'];
  const rows = opp.boq.items.map(item => [
    `"${item.itemCode}"`,
    `"${item.description.replace(/"/g, '""')}"`,
    `"${item.category}"`,
    item.quantity,
    `"${item.unit}"`,
    item.unitCost,
    item.unitListPrice,
    item.discountPercent,
    item.extendedPrice,
    item.marginPercent
  ]);

  const csv = [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
  downloadBlob(csv, `${opp.code}_BOQ_Pricing_v${opp.boq.version}.csv`, 'text/csv;charset=utf-8;');
}

/**
 * Export full pipeline table to CSV
 */
export function exportPipelineCSV(opportunities: Opportunity[]) {
  const headers = ['Code', 'Opportunity Name', 'Client', 'Industry', 'Region', 'Stage', 'Priority', 'TCV ($)', 'ARR ($)', 'Win Probability (%)', 'Tech Stack', 'Lead Architect', 'Sales KAM', 'POC Status', 'BOQ Margin (%)'];
  const rows = opportunities.map(o => [
    `"${o.code}"`,
    `"${o.name.replace(/"/g, '""')}"`,
    `"${o.clientName}"`,
    `"${o.clientIndustry}"`,
    `"${o.region}"`,
    `"${o.stage}"`,
    `"${o.priority}"`,
    o.contractValue,
    o.arr,
    o.winProbability,
    `"${o.primaryTechStack}"`,
    `"${o.leadSolutionArchitect}"`,
    `"${o.accountExecutive}"`,
    `"${o.poc.status}"`,
    o.boq.overallMarginPercent
  ]);

  const csv = [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
  downloadBlob(csv, `Presales_Pipeline_Export_${new Date().toISOString().slice(0, 10)}.csv`, 'text/csv;charset=utf-8;');
}
