import React from 'react';
import { Activity, AlertTriangle, ArrowRight, BarChart3, Building2, Calendar, CheckCircle2, Clock, Layers, MessageSquarePlus, Plus } from 'lucide-react';
import { ActiveTab, Opportunity } from '../../types';
import { formatCurrency } from '../../utils/currency';

interface MobileHomeScreenProps {
  opportunities: Opportunity[];
  onSelectOpportunity: (opportunity: Opportunity) => void;
  onNavigateTab: (tab: ActiveTab) => void;
  onOpenNewOpportunity: () => void;
}

export const MobileHomeScreen: React.FC<MobileHomeScreenProps> = ({ opportunities, onSelectOpportunity, onNavigateTab, onOpenNewOpportunity }) => {
  const active = opportunities.filter(o => !['closed_won', 'closed_lost', 'on_hold', 'cancelled'].includes(o.stage));
  const overdue = opportunities.flatMap(o => (o.actionItems || []).filter(item => !item.isCompleted && new Date(item.dueDate) < new Date()).map(item => ({ opportunity: o, item })));
  const followUps = opportunities.flatMap(o => (o.actionItems || []).filter(item => !item.isCompleted).map(item => ({ opportunity: o, item }))).sort((a, b) => new Date(a.item.dueDate).getTime() - new Date(b.item.dueDate).getTime());
  const pipeline = active.reduce((total, opportunity) => total + (opportunity.contractValue || 0), 0);

  return <div className="space-y-3 pb-2">
    <section className="bg-white border border-gray-200 rounded p-4">
      <div className="flex items-center gap-2"><Activity className="w-5 h-5 text-blue-600" /><div><h1 className="text-base font-bold text-gray-900">Presales Mobile Hub</h1><p className="text-xs text-gray-500">Live pipeline and next actions</p></div></div>
      <div className="grid grid-cols-2 gap-2 mt-4"><div className="rounded border border-blue-100 bg-blue-50 p-2.5"><div className="text-[10px] uppercase text-blue-700 font-semibold">Active Deals</div><div className="text-xl font-bold font-mono text-blue-900">{active.length}</div></div><div className="rounded border border-emerald-100 bg-emerald-50 p-2.5"><div className="text-[10px] uppercase text-emerald-700 font-semibold">Pipeline</div><div className="text-sm font-bold font-mono text-emerald-900 mt-1">{formatCurrency(pipeline)}</div></div><div className="rounded border border-amber-100 bg-amber-50 p-2.5"><div className="text-[10px] uppercase text-amber-700 font-semibold">Follow-ups</div><div className="text-xl font-bold font-mono text-amber-900">{followUps.length}</div></div><div className="rounded border border-red-100 bg-red-50 p-2.5"><div className="text-[10px] uppercase text-red-700 font-semibold">Overdue</div><div className="text-xl font-bold font-mono text-red-900">{overdue.length}</div></div></div>
    </section>

     <section className="grid grid-cols-2 gap-2"><button onClick={onOpenNewOpportunity} className="bg-blue-600 text-white rounded p-3 text-left"><Plus className="w-4 h-4" /><div className="text-xs font-semibold mt-2">New Opportunity</div><div className="text-[10px] text-blue-100">Start client intake</div></button><button onClick={() => onNavigateTab('mobile_capture')} className="bg-white border border-gray-200 rounded p-3 text-left"><MessageSquarePlus className="w-4 h-4 text-blue-600" /><div className="text-xs font-semibold text-gray-900 mt-2">Log Update</div><div className="text-[10px] text-gray-500">Record client work</div></button><button onClick={() => onNavigateTab('opportunities')} className="bg-white border border-gray-200 rounded p-3 text-left"><Layers className="w-4 h-4 text-blue-600" /><div className="text-xs font-semibold text-gray-900 mt-2">Deals Tracker</div><div className="text-[10px] text-gray-500">Open full workspaces</div></button><button onClick={() => onNavigateTab('action_center')} className="bg-white border border-gray-200 rounded p-3 text-left"><CheckCircle2 className="w-4 h-4 text-amber-600" /><div className="text-xs font-semibold text-gray-900 mt-2">Tasks</div><div className="text-[10px] text-gray-500">Review next actions</div></button><button onClick={() => onNavigateTab('clients')} className="bg-white border border-gray-200 rounded p-3 text-left"><Building2 className="w-4 h-4 text-purple-600" /><div className="text-xs font-semibold text-gray-900 mt-2">Clients</div><div className="text-[10px] text-gray-500">Open Client 360</div></button><button onClick={() => onNavigateTab('calendar')} className="bg-white border border-gray-200 rounded p-3 text-left"><Calendar className="w-4 h-4 text-emerald-600" /><div className="text-xs font-semibold text-gray-900 mt-2">Calendar</div><div className="text-[10px] text-gray-500">Sessions and deadlines</div></button><button onClick={() => onNavigateTab('analytics')} className="bg-white border border-gray-200 rounded p-3 text-left col-span-2"><BarChart3 className="w-4 h-4 text-cyan-600" /><div className="text-xs font-semibold text-gray-900 mt-2">Reports & Analytics</div><div className="text-[10px] text-gray-500">Activity and pipeline reporting</div></button></section>

    <section className="bg-white border border-gray-200 rounded p-3"><div className="flex items-center justify-between border-b border-gray-100 pb-2"><h2 className="text-xs font-bold uppercase tracking-wider text-gray-800">Upcoming Actions</h2><Clock className="w-4 h-4 text-gray-400" /></div>{followUps.length === 0 ? <div className="py-6 text-center text-xs text-gray-500">No pending follow-ups.</div> : <div className="divide-y divide-gray-100">{followUps.slice(0, 5).map(({ opportunity, item }) => <button key={`${opportunity.id}-${item.id}`} onClick={() => onSelectOpportunity(opportunity)} className="w-full text-left py-2.5"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><div className="text-xs font-semibold text-gray-900 truncate">{item.title}</div><div className="text-[10px] text-gray-500 mt-0.5">{opportunity.clientName} · {opportunity.code}</div></div><span className="text-[10px] font-mono text-amber-700 whitespace-nowrap">{item.dueDate}</span></div></button>)}</div>}</section>
    {overdue.length > 0 && <section className="bg-red-50 border border-red-200 rounded p-3"><div className="flex items-center gap-2 text-xs font-bold text-red-800"><AlertTriangle className="w-4 h-4" /> {overdue.length} overdue action{overdue.length === 1 ? '' : 's'}</div><button onClick={() => onNavigateTab('action_center')} className="inline-flex items-center gap-1 text-[11px] text-red-700 font-semibold mt-2">Review Action Center <ArrowRight className="w-3 h-3" /></button></section>}
  </div>;
};
