import React from 'react';
import { AlertTriangle, CheckCircle2, Clock, CheckSquare } from 'lucide-react';
import { Opportunity } from '../../types';
import { PriorityBadge } from '../common/Badge';

interface MobileActionCenterProps { opportunities: Opportunity[]; onSelectOpportunity: (opportunity: Opportunity) => void; onUpdateOpportunity: (opportunity: Opportunity) => void; }

export const MobileActionCenter: React.FC<MobileActionCenterProps> = ({ opportunities, onSelectOpportunity, onUpdateOpportunity }) => {
  const actions = opportunities.flatMap(opportunity => (opportunity.actionItems || []).map(item => ({ item, opportunity }))).filter(({ item }) => !item.isCompleted).sort((a, b) => new Date(a.item.dueDate).getTime() - new Date(b.item.dueDate).getTime());
  const overdue = actions.filter(({ item }) => new Date(item.dueDate) < new Date()).length;
  const toggle = (opportunity: Opportunity, id: string) => onUpdateOpportunity({ ...opportunity, actionItems: (opportunity.actionItems || []).map(item => item.id === id ? { ...item, isCompleted: true } : item), updatedAt: new Date().toISOString() });
  return <div className="space-y-3 pb-2"><header className="bg-white border border-gray-200 rounded p-3"><div className="flex items-center gap-2"><CheckSquare className="w-5 h-5 text-blue-600" /><div><h1 className="text-base font-bold text-gray-900">Tasks & Next Actions</h1><p className="text-xs text-gray-500">Review and complete active presales commitments.</p></div></div><div className="grid grid-cols-2 gap-2 mt-3"><div className="rounded bg-blue-50 border border-blue-100 p-2"><div className="text-[10px] uppercase text-blue-700 font-semibold">Pending</div><div className="text-xl font-bold font-mono text-blue-900">{actions.length}</div></div><div className="rounded bg-red-50 border border-red-100 p-2"><div className="text-[10px] uppercase text-red-700 font-semibold">Overdue</div><div className="text-xl font-bold font-mono text-red-900">{overdue}</div></div></div></header>{actions.length === 0 ? <div className="bg-white border border-dashed border-gray-300 rounded p-10 text-center"><CheckCircle2 className="w-8 h-8 mx-auto text-emerald-400" /><div className="mt-2 text-sm font-semibold text-gray-800">No pending actions</div><div className="text-xs text-gray-500 mt-1">New opportunity commitments will appear here.</div></div> : <div className="space-y-2">{actions.map(({ item, opportunity }) => { const isOverdue = new Date(item.dueDate) < new Date(); return <article key={`${opportunity.id}-${item.id}`} className={`bg-white border rounded p-3 space-y-2 ${isOverdue ? 'border-red-200' : 'border-gray-200'}`}><div className="flex items-start gap-2"><button onClick={() => toggle(opportunity, item.id)} className="mt-0.5"><CheckCircle2 className="w-4 h-4 text-gray-300" /></button><div className="min-w-0 flex-1"><button onClick={() => onSelectOpportunity(opportunity)} className="text-left text-sm font-semibold text-gray-900 break-words">{item.title}</button><div className="text-[11px] text-gray-500 mt-1">{opportunity.clientName} · {opportunity.code}</div></div><PriorityBadge priority={item.priority} /></div><div className="flex items-center justify-between text-[10px] text-gray-500"><span>{item.assignedTo}</span><span className={`inline-flex items-center gap-1 font-mono ${isOverdue ? 'text-red-700 font-bold' : 'text-amber-700'}`}><Clock className="w-3 h-3" />{item.dueDate}{isOverdue && <AlertTriangle className="w-3 h-3" />}</span></div></article>; })}</div>}</div>;
};
